{% set name = "enaml" %}
{% set version = "0.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d20e93a1b34e8d800a6218d4bcfa030d3294979c6f901285fc4d3c71fabdcec2

build:
  number: 0
  skip: true  # [py<310 or s390x]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv --no-build-isolation
  entry_points:
    - enaml-run = enaml.runner:main
    - enaml-compileall = enaml.compile_all:main
  osx_is_app: true

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools >=77.0
    - wheel
    - setuptools_scm >=3.4.3
    - cppy >=1.2.0
    - setuptools-scm >=3.4.3
  run:
    - python
    - python.app  # [osx]
    - pyqt
    - qtpy >=2.1.0
    - ply
    - atom >=0.9.0
    - kiwisolver >=1.2.0
    - bytecode >=0.17.0
    - pegen >=0.3.0
  run_constrained:
    - python !=3.11.0,!=3.11.1
    - qtpy >=2.3.0
    - PyQt6 >=6.3.1
    - pyside6 >=6.2.3

test:
  requires:
    - pip
  commands:
    - enaml-run --help
    - pip check
  imports:
    - enaml
    - enaml.callableref
    - enaml.weakmethod
    - enaml.signaling
    - enaml.colorext
    - enaml.core.alias
    - enaml.core.dynamicscope
    - enaml.core.funchelper
    - enaml.fontext
    - enaml.core.api
    - enaml.widgets.api
    - enaml.layout.api

about:
  home: https://github.com/nucleic/enaml
  description: |
    Enaml is a programming language and framework for creating
    professional-quality user interfaces with minimal effort.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Declarative DSL for building rich user interfaces in Python
  doc_url: https://enaml.readthedocs.io/
  dev_url: https://github.com/nucleic/enaml

extra:
  recipe-maintainers:
    - blink1073
    - licode
    - MatthieuDartiailh
    - tacaswell
    - marcelotrevisani
    - gabrielcnr
