{% set name = "enaml" %}
{% set version = "0.16.0" %}
{% set sha256 = "dee51e9099965de4dac3ba779a0852722ae7b1f1ae0f39f75dd15400171cd5a2" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [py<38 or ppc64le]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - enaml-run = enaml.runner:main
    - enaml-compileall = enaml.compile_all:main
  osx_is_app: true

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python >=3.6
    - setuptools
    - pip
    - atom >=0.6.0
    - kiwisolver >=1.2.0
    - ply >=3.4
    - qtpy >=1.3
    - cppy >=1.1.0
    - bytecode >=0.11.0
  run:
    - python >=3.6
    - python.app  # [osx]
    - atom >=0.6.0
    - pyqt
    - qtpy >=1.3
    - kiwisolver >=1.2.0
    - ply >=3.4
    - bytecode >=0.11.0

test:
  commands:
    - enaml-run --help
  imports:
    - enaml
    - enaml.callableref
    - enaml.weakmethod
    - enaml.signaling
    - enaml.colorext
    - enaml.core.alias
    - enaml.core.dynamicscope
    - enaml.core.funchelper
    - enaml.fontext
    - enaml.core.api
    - enaml.widgets.api
    - enaml.layout.api

about:
  home: https://github.com/nucleic/enaml
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Declarative DSL for building rich user interfaces in Python
  doc_url: http://nucleic.github.io/enaml/docs/
  dev_url: https://github.com/nucleic/enaml

extra:
  recipe-maintainers:
    - blink1073
    - licode
    - MatthieuDartiailh
    - tacaswell
