{% set name = "enaml" %}
{% set version = "0.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d20e93a1b34e8d800a6218d4bcfa030d3294979c6f901285fc4d3c71fabdcec2

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv --no-build-isolation
  skip: true  # [py<310]
  entry_points:
    - enaml-run = enaml.runner:main
    - enaml-compileall = enaml.compile_all:main

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools >=77.0
    - wheel
    - setuptools_scm >=3.4.3
    - toml
    - cppy >=1.2.0
  run:
    - python
    - atom >=0.9.0
    - kiwisolver >=1.2.0
    - bytecode >=0.17.0
    - pegen >=0.3.0
  run_constrained:
    - python !=3.11.0,!=3.11.1
    - qtpy >=2.3.0
    - pyqt >=6.3.1
    - pyside6 >=6.2.3

test:
  source_files:
    - tests
  imports:
    - enaml
    - enaml.callableref
    - enaml.weakmethod
    - enaml.signaling
    - enaml.colorext
    - enaml.core.alias
    - enaml.core.dynamicscope
    - enaml.core.funchelper
    - enaml.fontext
    - enaml.core.api
    - enaml.widgets.api
    - enaml.layout.api
  requires:
    - pip
    - pytest
  commands:
    - enaml-run --help
    - enaml-compileall --help
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v tests

about:
  home: https://github.com/nucleic/enaml
  description: |
    Enaml is a programming language and framework for creating
    professional-quality user interfaces with minimal effort.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Declarative DSL for building rich user interfaces in Python
  doc_url: https://enaml.readthedocs.io
  dev_url: https://github.com/nucleic/enaml

extra:
  recipe-maintainers:
    - blink1073
    - licode
    - MatthieuDartiailh
    - tacaswell
    - marcelotrevisani
    - gabrielcnr
