{% set name = "enaml" %}
{% set version = "0.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7015a263c1c96e8d59891009a053b904a33e09f52842907bec0c574799bfe3ce

build:
  number: 1
  skip: true  # [py<38 or py!=3.11.0 or py!=3.11.1 or s390x]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv --no-build-isolation
  entry_points:
    - enaml-run = enaml.runner:main
    - enaml-compileall = enaml.compile_all:main
  osx_is_app: true

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
    - setuptools_scm
    - toml
    - cppy 1.2.1
    - bytecode 0.14.0
  run:
    - python
    - python.app  # [osx]
    - pyqt
    - qtpy >=2.1.0
    - ply
    - atom >=0.9.0
    - kiwisolver >=1.2.0
    - bytecode >=0.13.0
    - pegen >=0.1.0

test:
  requires:
    - pip
  commands:
    - enaml-run --help
    - pip check
  imports:
    - enaml
    - enaml.callableref
    - enaml.weakmethod
    - enaml.signaling
    - enaml.colorext
    - enaml.core.alias
    - enaml.core.dynamicscope
    - enaml.core.funchelper
    - enaml.fontext
    - enaml.core.api
    - enaml.widgets.api
    - enaml.layout.api

about:
  home: https://github.com/nucleic/enaml
  description: |
    Enaml is a programming language and framework for creating
    professional-quality user interfaces with minimal effort.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Declarative DSL for building rich user interfaces in Python
  doc_url: https://enaml.readthedocs.io/
  dev_url: https://github.com/nucleic/enaml

extra:
  recipe-maintainers:
    - blink1073
    - licode
    - MatthieuDartiailh
    - tacaswell
    - marcelotrevisani
    - gabrielcnr
